name: genie_cart_delivery
description: Delivery App for GenieMart
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+12
  fluttertoast: ^7.1.1
  cloud_firestore: ^0.14.1+3
  firebase_database: ^4.1.1
  firebase_storage: ^4.0.1
  firebase_core: ^0.5.0
  firebase_auth:
  firebase_auth_web:
  cloud_firestore_web:
  firebase_core_web: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
